# **NumPy Library**

**NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.**

***Important Concepts***

In [1]:
#current working directory location

import os
cwd=os.getcwd()
cwd

'C:\\Users\\RITIK\\OneDrive\\Desktop\\Python programs\\Jupyter Notebook\\NumPy'

In [2]:
#importing numpy library

import numpy as np



**1. Conversion from other Python structures (i.e. lists and tuples)**

In [3]:
#creating an array

myarr=np.array([[3,4,5,6]],np.int32)
myarr

array([[3, 4, 5, 6]])

In [4]:
#2d array

myarr.shape

(1, 4)

In [5]:
# accessing 0th row and 0th column element

myarr[0,0]


3

In [6]:
# accessing 0th row and 1st column element

myarr[0,1]

4

In [7]:
myarr.dtype

dtype('int32')

In [8]:
#updating the whole array

myarr[0]=[1,2,3,4]
myarr

array([[1, 2, 3, 4]])

In [9]:
#updating specific position of array

myarr[0,1]=42
myarr

array([[ 1, 42,  3,  4]])

In [10]:
# creating 2d array

arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],np.int64)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [11]:
arr2.shape

(4, 3)

In [12]:
arr2[1,2]  #row=0, column=2

6

**2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [13]:
#1d array

arr=np.arange(2,9,2)  #start,stop,step
arr


array([2, 4, 6, 8])

In [14]:
arr=np.arange(2,4,0.6)
arr

array([2. , 2.6, 3.2, 3.8])

In [15]:
#linspace(start, stop, numbers to generate)
arr = np.linspace(1.,6.,3)
arr

array([1. , 3.5, 6. ])

In [16]:
# 2d Array

arr=np.eye(4,3)  #eye(n,m) creates a 2d array with 1 where i=j and rest are 0s
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
#zeros(number of matrice, row, column)

arr = np.zeros((3,4,2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
# Uisng ones

arr = np.ones((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#ones (number of matrice, row, column

arr = np.ones((2,4,2))
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr = arr.reshape(3,33)
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
arr = arr.ravel()  # converts into 1d array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr.shape

(99,)

In [25]:
x = 28
arr = np.arange(x).reshape(4,7)
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [26]:
x = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# sum of column

arr.sum(axis = 0)

array([12, 15, 18])

In [28]:
# sum of row 

arr.sum(axis = 1)

array([ 6, 15, 24])

In [29]:
#Transpose of a matrix

arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
arr.ndim

2

In [31]:
arr.size

9

In [32]:
arr.shape

(3, 3)

In [33]:
arr = np.array([25,21,10,1,36,4])
print(arr)
print(f'shape of array: {arr.shape}')

[25 21 10  1 36  4]
shape of array: (6,)


In [34]:
arr.argmax()  #returns Indeces

4

In [35]:
arr.argmin()

3

In [36]:
print(arr.argsort())
print(f'Here it will return sorted index -- first value should be of index = 3 i.e, value=1, simliaryly ')

[3 5 2 1 0 4]
Here it will return sorted index -- first value should be of index = 3 i.e, value=1, simliaryly 


In [37]:
arr = np.array([[1,4,8],[5,7,3],[12,41,0],[10,14,30]])
arr

array([[ 1,  4,  8],
       [ 5,  7,  3],
       [12, 41,  0],
       [10, 14, 30]])

In [38]:
arr.argmin()

8

In [39]:
arr.argmax()

7

In [40]:
arr1 = arr.copy()
arr1.sort()
arr1

array([[ 1,  4,  8],
       [ 3,  5,  7],
       [ 0, 12, 41],
       [10, 14, 30]])

In [41]:
arr.argmax(axis = 0)

array([2, 2, 3], dtype=int64)

In [42]:
arr.argmax(axis = 1)

array([2, 1, 1, 2], dtype=int64)

In [43]:
arr.max()

41

In [44]:
arr.min()

0

In [45]:
arr.sum()

135

**Remember : Arg return index while other return values**

#  Matrix Operation

In [46]:
arr1 = np.array([[1,5,6],[1,46,25],[45,32,4]])
arr1

array([[ 1,  5,  6],
       [ 1, 46, 25],
       [45, 32,  4]])

In [47]:
arr2 = np.array([[15,20,30],[21,20,35],[74,54,65]])
arr2

array([[15, 20, 30],
       [21, 20, 35],
       [74, 54, 65]])

In [48]:
# Sum of Arrays
%time
print(f'sum of array 1 and 2 is: \n', arr1+arr2)

CPU times: total: 0 ns
Wall time: 0 ns
sum of array 1 and 2 is: 
 [[ 16  25  36]
 [ 22  66  60]
 [119  86  69]]


In [49]:
print(f'difference of array 1 and 2 is: \n', arr2 - arr1)

difference of array 1 and 2 is: 
 [[ 14  15  24]
 [ 20 -26  10]
 [ 29  22  61]]


In [50]:
arr1 * arr2

array([[  15,  100,  180],
       [  21,  920,  875],
       [3330, 1728,  260]])

In [51]:
arr = np.array([[4,9,16],[25,36,49],[64,81,100]],np.int32)
arr

array([[  4,   9,  16],
       [ 25,  36,  49],
       [ 64,  81, 100]])

In [52]:
np.sqrt(arr)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [53]:
np.where(arr>50)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [54]:
type(np.where(arr>20))

tuple

In [55]:
np.count_nonzero(arr)

9

In [56]:
arr

array([[  4,   9,  16],
       [ 25,  36,  49],
       [ 64,  81, 100]])

In [57]:
index = np.where(arr == 49)
arr[index] = 0
arr

array([[  4,   9,  16],
       [ 25,  36,   0],
       [ 64,  81, 100]])

In [58]:
arr[2,2] = 0
arr

array([[ 4,  9, 16],
       [25, 36,  0],
       [64, 81,  0]])

In [59]:
np.count_nonzero(arr)

7

In [60]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

**Random Numbers**

In [61]:
arr = np.random.rand(3,2)
arr

array([[0.72948412, 0.36167813],
       [0.44017021, 0.5056319 ],
       [0.47227235, 0.52154049]])

In [62]:
arr = np.random.randint(5,size=10)
arr

array([1, 4, 0, 1, 0, 2, 1, 0, 1, 1])

In [63]:
arr = np.random.randint(15,size=(3,3))
arr

array([[12,  1, 13],
       [10,  8, 13],
       [11, 13,  5]])

**Difference between Numpy and List**

In [64]:
import sys

In [65]:
py_arr = [12112551,141211125,342215145,651551518,31515654,215515,41441484]

In [66]:
np_arr = np.array(py_arr)

In [67]:
sys.getsizeof(1) * len(arr)

84

In [68]:
np_arr.itemsize * np_arr.size

28